services:
  web:
    build:
      context: .
      dockerfile: dockerfile/Dockerfile
    ports:
      - "9595:80"
    networks:
      - web-network
    volumes:
      - ./html:/usr/share/nginx/html

  db:
    image: mariadb:latest
    networks:
      - web-network
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - web-db-data:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - "8585:8080"
    networks:
      - web-network

volumes:
  web-db-data:

networks:
  web-network:

